# Generated by Django 2.1.3 on 2019-03-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Описание')),
                ('first', models.TextField(verbose_name='Первый ответ')),
                ('second', models.TextField(verbose_name='Второй ответ')),
                ('third', models.TextField(verbose_name='Третий ответ')),
                ('forth', models.TextField(verbose_name='Четвертый ответ')),
                ('answ', models.TextField(verbose_name='Ответ')),
                ('nameSubjects', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='subjects.Subject', verbose_name='Какой предмет')),
            ],
        ),
    ]
