# Generated by Django 2.1.3 on 2019-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20190301_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['nameSubjects'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='nameSubjects', max_length=100, verbose_name='Предмет'),
        ),
    ]
