# Generated by Django 2.1.3 on 2019-03-01 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20190301_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.CharField(default='', max_length=100, verbose_name='Картинка (название с расширением)'),
        ),
        migrations.AddField(
            model_name='task',
            name='in_put',
            field=models.BooleanField(default=False, verbose_name='Ответ текстом'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='subjects.Subject', verbose_name='Какой предмет'), max_length=100, verbose_name='Предмет'),
        ),
    ]
