# Generated by Django 2.1.3 on 2019-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20190301_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='forth',
            field=models.TextField(blank=True, verbose_name='Четвертый ответ'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Картинка (название с расширением)'),
        ),
    ]
