# Generated by Django 2.1.3 on 2019-03-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20190302_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Предмет(не обязательно)'),
        ),
        migrations.AddField(
            model_name='task',
            name='nameLevel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='subjects.Level', verbose_name='Какой уровень'),
        ),
    ]
