# Generated by Django 2.1.3 on 2019-03-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20190302_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
    ]
