# Generated by Django 2.1.3 on 2019-03-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_auto_20190302_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, upload_to='subjects/static/media', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='nameLevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.Level', verbose_name='Какой уровень'),
        ),
        migrations.AlterField(
            model_name='task',
            name='nameSubjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.Subject', verbose_name='Какой предмет'),
        ),
    ]
