# Generated by Django 2.1.3 on 2019-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_auto_20190302_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='img',
            field=models.ImageField(blank=True, upload_to='subjects/photo', verbose_name='Картинка'),
        ),
    ]
