# Generated by Django 2.1.3 on 2019-03-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
