# Generated by Django 2.2.6 on 2020-01-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0022_math'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='math',
            options={'verbose_name': 'Математика', 'verbose_name_plural': 'Математика'},
        ),
    ]
