# Generated by Django 2.2.6 on 2020-01-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0024_russia_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='nameLevel',
        ),
        migrations.RemoveField(
            model_name='task',
            name='nameSubjects',
        ),
        migrations.AddField(
            model_name='math',
            name='answ',
            field=models.TextField(default='', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='numberVariant',
            field=models.TextField(default='', verbose_name='Название варианта'),
        ),
        migrations.AddField(
            model_name='math',
            name='task',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ',
            field=models.TextField(default='', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='numberVariant',
            field=models.TextField(default='', verbose_name='Название варианта'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ',
            field=models.TextField(default='', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='numberVariant',
            field=models.TextField(default='', verbose_name='Название варианта'),
        ),
        migrations.AddField(
            model_name='social',
            name='task',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
