# Generated by Django 2.2.6 on 2020-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0025_auto_20200108_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='numberVariant',
            field=models.CharField(max_length=100, verbose_name='Название варианта'),
        ),
        migrations.AlterField(
            model_name='russia',
            name='numberVariant',
            field=models.CharField(default='', max_length=100, verbose_name='Название варианта'),
        ),
        migrations.AlterField(
            model_name='social',
            name='numberVariant',
            field=models.CharField(default='', max_length=100, verbose_name='Название варианта'),
        ),
    ]
