# Generated by Django 2.2.6 on 2020-01-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0026_auto_20200108_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='math',
            old_name='task',
            new_name='task1',
        ),
        migrations.RemoveField(
            model_name='math',
            name='answ',
        ),
        migrations.AddField(
            model_name='math',
            name='answ1',
            field=models.CharField(default='', max_length=100, verbose_name='Ответ'),
        ),
    ]
