# Generated by Django 2.2.6 on 2020-01-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0027_auto_20200108_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='answ1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='math',
            name='task1',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
