# Generated by Django 2.2.6 on 2020-01-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0028_auto_20200108_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='answ2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='task2',
            field=models.TextField(blank=True, default='', verbose_name='Задание 2'),
        ),
        migrations.AlterField(
            model_name='math',
            name='task1',
            field=models.TextField(blank=True, default='', verbose_name='Задание 1'),
        ),
    ]
