# Generated by Django 2.2.6 on 2020-01-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0029_auto_20200108_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='russia',
            name='answ',
        ),
        migrations.RemoveField(
            model_name='russia',
            name='task',
        ),
        migrations.RemoveField(
            model_name='social',
            name='answ',
        ),
        migrations.RemoveField(
            model_name='social',
            name='task',
        ),
        migrations.AddField(
            model_name='russia',
            name='answ1',
            field=models.TextField(blank=True, default='', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task1',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ1',
            field=models.TextField(blank=True, default='', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='task1',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='russia',
            name='numberVariant',
            field=models.CharField(max_length=100, verbose_name='Название варианта'),
        ),
    ]
