# Generated by Django 2.2.6 on 2020-01-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0030_auto_20200108_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='answ10',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ12',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ13',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ14',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ15',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ16',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ17',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ18',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ19',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ6',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ7',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ8',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='answ9',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='task10',
            field=models.TextField(blank=True, default='', verbose_name='Задание 11'),
        ),
        migrations.AddField(
            model_name='math',
            name='task11',
            field=models.TextField(blank=True, default='', verbose_name='Задание 12'),
        ),
        migrations.AddField(
            model_name='math',
            name='task13',
            field=models.TextField(blank=True, default='', verbose_name='Задание 13'),
        ),
        migrations.AddField(
            model_name='math',
            name='task14',
            field=models.TextField(blank=True, default='', verbose_name='Задание 14'),
        ),
        migrations.AddField(
            model_name='math',
            name='task15',
            field=models.TextField(blank=True, default='', verbose_name='Задание 15'),
        ),
        migrations.AddField(
            model_name='math',
            name='task16',
            field=models.TextField(blank=True, default='', verbose_name='Задание 16'),
        ),
        migrations.AddField(
            model_name='math',
            name='task17',
            field=models.TextField(blank=True, default='', verbose_name='Задание 17'),
        ),
        migrations.AddField(
            model_name='math',
            name='task18',
            field=models.TextField(blank=True, default='', verbose_name='Задание 18'),
        ),
        migrations.AddField(
            model_name='math',
            name='task19',
            field=models.TextField(blank=True, default='', verbose_name='Задание 19'),
        ),
        migrations.AddField(
            model_name='math',
            name='task3',
            field=models.TextField(blank=True, default='', verbose_name='Задание 3'),
        ),
        migrations.AddField(
            model_name='math',
            name='task4',
            field=models.TextField(blank=True, default='', verbose_name='Задание 4'),
        ),
        migrations.AddField(
            model_name='math',
            name='task5',
            field=models.TextField(blank=True, default='', verbose_name='Задание 5'),
        ),
        migrations.AddField(
            model_name='math',
            name='task6',
            field=models.TextField(blank=True, default='', verbose_name='Задание 6'),
        ),
        migrations.AddField(
            model_name='math',
            name='task7',
            field=models.TextField(blank=True, default='', verbose_name='Задание 7'),
        ),
        migrations.AddField(
            model_name='math',
            name='task8',
            field=models.TextField(blank=True, default='', verbose_name='Задание 8'),
        ),
        migrations.AddField(
            model_name='math',
            name='task9',
            field=models.TextField(blank=True, default='', verbose_name='Задание 9'),
        ),
    ]
