# Generated by Django 2.2.6 on 2020-01-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0031_auto_20200108_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='answ11',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='math',
            name='task12',
            field=models.TextField(blank=True, default='', verbose_name='Задание 12'),
        ),
        migrations.AlterField(
            model_name='math',
            name='task10',
            field=models.TextField(blank=True, default='', verbose_name='Задание 10'),
        ),
        migrations.AlterField(
            model_name='math',
            name='task11',
            field=models.TextField(blank=True, default='', verbose_name='Задание 11'),
        ),
    ]
