# Generated by Django 2.2.6 on 2020-01-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0033_auto_20200108_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='russia',
            name='answ10',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ11',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ12',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ13',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ14',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ15',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ16',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ17',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ18',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ19',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ20',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ21',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ22',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ23',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ24',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ25',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ26',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ27',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ7',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ8',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='answ9',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task10',
            field=models.TextField(blank=True, default='', verbose_name='Задание 10'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task11',
            field=models.TextField(blank=True, default='', verbose_name='Задание 11'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task12',
            field=models.TextField(blank=True, default='', verbose_name='Задание 12'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task13',
            field=models.TextField(blank=True, default='', verbose_name='Задание 13'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task14',
            field=models.TextField(blank=True, default='', verbose_name='Задание 14'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task15',
            field=models.TextField(blank=True, default='', verbose_name='Задание 15'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task16',
            field=models.TextField(blank=True, default='', verbose_name='Задание 16'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task17',
            field=models.TextField(blank=True, default='', verbose_name='Задание 17'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task18',
            field=models.TextField(blank=True, default='', verbose_name='Задание 18'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task19',
            field=models.TextField(blank=True, default='', verbose_name='Задание 19'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task20',
            field=models.TextField(blank=True, default='', verbose_name='Задание 20'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task21',
            field=models.TextField(blank=True, default='', verbose_name='Задание 21'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task22',
            field=models.TextField(blank=True, default='', verbose_name='Задание 22'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task23',
            field=models.TextField(blank=True, default='', verbose_name='Задание 23'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task24',
            field=models.TextField(blank=True, default='', verbose_name='Задание 24'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task25',
            field=models.TextField(blank=True, default='', verbose_name='Задание 25'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task26',
            field=models.TextField(blank=True, default='', verbose_name='Задание 26'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task27',
            field=models.TextField(blank=True, default='', verbose_name='Задание 27'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task7',
            field=models.TextField(blank=True, default='', verbose_name='Задание 7'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task8',
            field=models.TextField(blank=True, default='', verbose_name='Задание 8'),
        ),
        migrations.AddField(
            model_name='russia',
            name='task9',
            field=models.TextField(blank=True, default='', verbose_name='Задание 9'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ10',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ11',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ12',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ13',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ14',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ15',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ16',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ17',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ18',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ19',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ20',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ21',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ22',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ23',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ24',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ25',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ26',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ27',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ28',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ29',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ7',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ8',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='answ9',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='social',
            name='task10',
            field=models.TextField(blank=True, default='', verbose_name='Задание 10'),
        ),
        migrations.AddField(
            model_name='social',
            name='task11',
            field=models.TextField(blank=True, default='', verbose_name='Задание 11'),
        ),
        migrations.AddField(
            model_name='social',
            name='task12',
            field=models.TextField(blank=True, default='', verbose_name='Задание 12'),
        ),
        migrations.AddField(
            model_name='social',
            name='task13',
            field=models.TextField(blank=True, default='', verbose_name='Задание 13'),
        ),
        migrations.AddField(
            model_name='social',
            name='task14',
            field=models.TextField(blank=True, default='', verbose_name='Задание 14'),
        ),
        migrations.AddField(
            model_name='social',
            name='task15',
            field=models.TextField(blank=True, default='', verbose_name='Задание 15'),
        ),
        migrations.AddField(
            model_name='social',
            name='task16',
            field=models.TextField(blank=True, default='', verbose_name='Задание 16'),
        ),
        migrations.AddField(
            model_name='social',
            name='task17',
            field=models.TextField(blank=True, default='', verbose_name='Задание 17'),
        ),
        migrations.AddField(
            model_name='social',
            name='task18',
            field=models.TextField(blank=True, default='', verbose_name='Задание 18'),
        ),
        migrations.AddField(
            model_name='social',
            name='task19',
            field=models.TextField(blank=True, default='', verbose_name='Задание 19'),
        ),
        migrations.AddField(
            model_name='social',
            name='task20',
            field=models.TextField(blank=True, default='', verbose_name='Задание 20'),
        ),
        migrations.AddField(
            model_name='social',
            name='task21',
            field=models.TextField(blank=True, default='', verbose_name='Задание 21'),
        ),
        migrations.AddField(
            model_name='social',
            name='task22',
            field=models.TextField(blank=True, default='', verbose_name='Задание 22'),
        ),
        migrations.AddField(
            model_name='social',
            name='task23',
            field=models.TextField(blank=True, default='', verbose_name='Задание 23'),
        ),
        migrations.AddField(
            model_name='social',
            name='task24',
            field=models.TextField(blank=True, default='', verbose_name='Задание 24'),
        ),
        migrations.AddField(
            model_name='social',
            name='task25',
            field=models.TextField(blank=True, default='', verbose_name='Задание 25'),
        ),
        migrations.AddField(
            model_name='social',
            name='task26',
            field=models.TextField(blank=True, default='', verbose_name='Задание 26'),
        ),
        migrations.AddField(
            model_name='social',
            name='task27',
            field=models.TextField(blank=True, default='', verbose_name='Задание 27'),
        ),
        migrations.AddField(
            model_name='social',
            name='task28',
            field=models.TextField(blank=True, default='', verbose_name='Задание 28'),
        ),
        migrations.AddField(
            model_name='social',
            name='task29',
            field=models.TextField(blank=True, default='', verbose_name='Задание 29'),
        ),
        migrations.AddField(
            model_name='social',
            name='task7',
            field=models.TextField(blank=True, default='', verbose_name='Задание 7'),
        ),
        migrations.AddField(
            model_name='social',
            name='task8',
            field=models.TextField(blank=True, default='', verbose_name='Задание 8'),
        ),
        migrations.AddField(
            model_name='social',
            name='task9',
            field=models.TextField(blank=True, default='', verbose_name='Задание 9'),
        ),
        migrations.AlterField(
            model_name='russia',
            name='task1',
            field=models.TextField(blank=True, default='', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='social',
            name='task1',
            field=models.TextField(blank=True, default='', verbose_name='Задание'),
        ),
    ]
